const AppModel = {
  data: null,
  
  async load() {
    try {
      const response = await fetch('data/dynasty.json');
      this.data = await response.json();
      return this.data;
    } catch (e) {
      console.error('Failed to load dynasty data', e);
      return null;
    }
  },

  getNewsByCategory(category) {
    if (!this.data) return [];
    const stories = this.data.stories.filter(s => s.category === category);
    const headlines = this.data.headlines.filter(h => h.category === category);
    return [...stories, ...headlines];
  },

  getRankLookup(week) {
    const weekly = this.data.weeklyRankings.find(w => w.week === week) || this.data.weeklyRankings[0];
    return new Map(weekly.rankings.map(t => [t.team.toLowerCase(), t.rank]));
  },

  escapeHtml(value) {
    return String(value ?? '').replace(/[&<>"']/g, (char) => ({
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;'
    })[char]);
  },

  teamLogos: {
    'air force': 'FBS-Logo-Library/CFB%20Logos/Air_Force_Falcons_logo-300x300.png',
    'akron': 'FBS-Logo-Library/CFB%20Logos/Akron_Zips_logo-300x300.png',
    'alabama': 'FBS-Logo-Library/CFB%20Logos/Alabama_Crimson_Tide_logo-300x300.png',
    'appalachian state': 'FBS-Logo-Library/CFB%20Logos/Appalachian_State_Mountaineers_logo-300x300.png',
    'arizona': 'FBS-Logo-Library/CFB%20Logos/Arizona_Wildcats_logo-300x300.png',
    'arizona state': 'FBS-Logo-Library/CFB%20Logos/Arizona_State_Sun_Devils_logo-300x300.png',
    'arkansas': 'FBS-Logo-Library/CFB%20Logos/Arkansas_Razorbacks_logo-300x300.png',
    'arkansas state': 'FBS-Logo-Library/CFB%20Logos/Arkansas_State_Red_Wolves_logo-300x300.png',
    'army': 'FBS-Logo-Library/CFB%20Logos/Army_West_Point_Black_Knights_logo-300x300.png',
    'auburn': 'FBS-Logo-Library/CFB%20Logos/Auburn_Tigers_logo-300x300.png',
    'ball state': 'FBS-Logo-Library/CFB%20Logos/Ball_State_Cardinals_logo-300x300.png',
    'baylor': 'FBS-Logo-Library/CFB%20Logos/Baylor_Bears_logo-300x300.png',
    'boise state': 'FBS-Logo-Library/CFB%20Logos/Boise_State_Broncos_Logo-300x300.png',
    'boston college': 'FBS-Logo-Library/CFB%20Logos/Boston_College_Eagles_logo-300x300.png',
    'bowling green': 'FBS-Logo-Library/CFB%20Logos/Bowling_Green_Falcons_logo-300x300.png',
    'buffalo': 'FBS-Logo-Library/CFB%20Logos/Buffalo_Bulls_logo-300x300.png',
    'byu': 'FBS-Logo-Library/CFB%20Logos/BYU_Cougars_logo-300x300.png',
    'california': 'FBS-Logo-Library/CFB%20Logos/California_Golden_Bears_logo-300x300.png',
    'central michigan': 'FBS-Logo-Library/CFB%20Logos/Central_Michigan_Chippewas_logo-300x300.png',
    'charlotte': 'FBS-Logo-Library/CFB%20Logos/Charlotte_49ers_logo-300x300.png',
    'cincinnati': 'FBS-Logo-Library/CFB%20Logos/Cincinnati_Bearcats_logo-300x300.png',
    'clemson': 'FBS-Logo-Library/CFB%20Logos/Clemson_Tigers_logo-300x300.png',
    'coastal carolina': 'FBS-Logo-Library/CFB%20Logos/Coastal_Carolina_Chanticleers_logo-300x300.png',
    'colorado': 'FBS-Logo-Library/CFB%20Logos/Colorado_Buffaloes_logo-300x300.png',
    'colorado state': 'FBS-Logo-Library/CFB%20Logos/Colorado_State_Rams_logo-300x300.png',
    'duke': 'FBS-Logo-Library/CFB%20Logos/Duke_Blue_Devils_logo-300x300.png',
    'east carolina': 'FBS-Logo-Library/CFB%20Logos/East_Carolina_Pirates_logo-300x300.png',
    'eastern michigan': 'FBS-Logo-Library/CFB%20Logos/Eastern_Michigan_Eagles_logo-300x300.png',
    'florida atlantic': 'FBS-Logo-Library/CFB%20Logos/Florida_Atlantic_Owls_logo-300x300.png',
    'fiu': 'FBS-Logo-Library/CFB%20Logos/FIU-Panthers-Logo-300x300.png',
    'florida': 'FBS-Logo-Library/CFB%20Logos/Florida_Gators_logo-300x300.png',
    'florida state': 'FBS-Logo-Library/CFB%20Logos/Florida_State_Seminoles_logo-300x300.png',
    'fresno state': 'FBS-Logo-Library/CFB%20Logos/Fresno_State_Bulldogs_logo-300x300.png',
    'georgia': 'FBS-Logo-Library/CFB%20Logos/Georgia_Bulldogs_logo-300x300.png',
    'georgia southern': 'FBS-Logo-Library/CFB%20Logos/Georgia_Southern_Eagles_logo-300x300.png',
    'georgia state': 'FBS-Logo-Library/CFB%20Logos/Georgia_State_Panthers_logo-300x300.png',
    'georgia tech': 'FBS-Logo-Library/CFB%20Logos/Georgia_Tech_Yellow_Jackets_logo-300x300.png',
    'hawaiʻi': 'FBS-Logo-Library/CFB%20Logos/Hawaii_Rainbow_Warriors_logo-300x300.png',
    'houston': 'FBS-Logo-Library/CFB%20Logos/Houston_Cougars_logo-300x300.png',
    'illinois': 'FBS-Logo-Library/CFB%20Logos/Illinois_Fighting_Illini_logo-300x300.png',
    'indiana': 'FBS-Logo-Library/CFB%20Logos/Indiana_Hoosiers_logo-300x300.png',
    'iowa': 'FBS-Logo-Library/CFB%20Logos/Iowa_Hawkeyes_logo-300x300.png',
    'iowa state': 'FBS-Logo-Library/CFB%20Logos/Iowa_State_Cyclones_logo-300x300.png',
    'jacksonville state': 'FBS-Logo-Library/CFB%20Logos/Jacksonville-State-Gamecocks-logo-300x300.png',
    'james madison': 'FBS-Logo-Library/CFB%20Logos/James_Madison_Dukes_logo-300x300.png',
    'kansas': 'FBS-Logo-Library/CFB%20Logos/Kansas_Jayhawks_logo-300x300.png',
    'kansas state': 'FBS-Logo-Library/CFB%20Logos/Kansas_State_Wildcats_logo-300x300.png',
    'kennesaw state': 'FBS-Logo-Library/CFB%20Logos/Kennesaw-State-Owls-logo-300x300.png',
    'kent state': 'FBS-Logo-Library/CFB%20Logos/Kent_State_Golden_Flashes-300x300.png',
    'kentucky': 'FBS-Logo-Library/CFB%20Logos/Kentucky_Wildcats_logo-300x300.png',
    'liberty': 'FBS-Logo-Library/CFB%20Logos/Liberty_Flames_logo-300x300.png',
    'louisiana': 'FBS-Logo-Library/CFB%20Logos/Louisiana-Lafayette_Ragin_Cajuns_logo-300x300.png',
    'louisiana tech': 'FBS-Logo-Library/CFB%20Logos/Louisiana_Tech_Bulldogs_logo-300x300.png',
    'louisville': 'FBS-Logo-Library/CFB%20Logos/Louisville_Cardinals_logo-300x300.png',
    'lsu': 'FBS-Logo-Library/CFB%20Logos/LSU_Tigers-300x300.png',
    'marshall': 'FBS-Logo-Library/CFB%20Logos/Marshall_Thundering_Herd_logo-300x300.png',
    'maryland': 'FBS-Logo-Library/CFB%20Logos/Maryland_Terrapins_logo-300x300.png',
    'memphis': 'FBS-Logo-Library/CFB%20Logos/Memphis_Tigers_logo-300x300.png',
    'miami': 'FBS-Logo-Library/CFB%20Logos/Miami_Hurricanes_logo-300x300.png',
    'miami (oh)': 'FBS-Logo-Library/CFB%20Logos/Miami_OH_Redhawks_logo-300x300.png',
    'michigan': 'FBS-Logo-Library/CFB%20Logos/Michigan_Wolverines_logo-300x300.png',
    'michigan state': 'FBS-Logo-Library/CFB%20Logos/Michigan_State_Spartans_logo-300x300.png',
    'middle tennessee': 'FBS-Logo-Library/CFB%20Logos/Middle-Tennessee-Blue-Raiders-logo-300x300.png',
    'minnesota': 'FBS-Logo-Library/CFB%20Logos/Minnesota_Golden_Gophers_logo-300x300.png',
    'mississippi state': 'FBS-Logo-Library/CFB%20Logos/Mississippi_State_Bulldogs_logo-300x300.png',
    'missouri': 'FBS-Logo-Library/CFB%20Logos/Missouri_Tigers_logo-300x300.png',
    'navy': 'FBS-Logo-Library/CFB%20Logos/Navy_Midshipmen_logo-300x300.png',
    'nc state': 'FBS-Logo-Library/CFB%20Logos/North_Carolina_State_Wolfpack_logo-300x300.png',
    'nebraska': 'FBS-Logo-Library/CFB%20Logos/Nebraska_Cornhuskers_logo-300x300.png',
    'nevada': 'FBS-Logo-Library/CFB%20Logos/Nevada_Wolf_Pack_logo-300x300.png',
    'new mexico': 'FBS-Logo-Library/CFB%20Logos/New_Mexico_Lobos_logo-300x300.png',
    'new mexico state': 'FBS-Logo-Library/CFB%20Logos/New_Mexico_State_Aggies_logo-300x300.png',
    'north carolina': 'FBS-Logo-Library/CFB%20Logos/North_Carolina_Tar_Heels_logo-300x300.png',
    'north texas': 'FBS-Logo-Library/CFB%20Logos/North_Texas_Mean_Green_logo-300x300.png',
    'northern illinois': 'FBS-Logo-Library/CFB%20Logos/Northern_Illinois_Huskies-300x300.png',
    'northwestern': 'FBS-Logo-Library/CFB%20Logos/Northwestern_Wildcats_logo-300x300.png',
    'notre dame': 'FBS-Logo-Library/CFB%20Logos/Notre_Dame_Fighting_Irish_logo-300x300.png',
    'ohio': 'FBS-Logo-Library/CFB%20Logos/Ohio_Bobcats_logo-300x300.png',
    'ohio state': 'FBS-Logo-Library/CFB%20Logos/Ohio_State_Buckeyes_logo-300x300.png',
    'oklahoma': 'FBS-Logo-Library/CFB%20Logos/Oklahoma_Sooners_logo-300x300.png',
    'oklahoma state': 'FBS-Logo-Library/CFB%20Logos/Oklahoma_State_Cowboys_logo-300x300.png',
    'old dominion': 'FBS-Logo-Library/CFB%20Logos/Old_Dominion_Monarchs_logo-300x300.png',
    'ole miss': 'FBS-Logo-Library/CFB%20Logos/Ole_Miss_Rebels_logo-300x300.png',
    'oregon': 'FBS-Logo-Library/CFB%20Logos/Oregon_Ducks_logo-300x300.png',
    'oregon state': 'FBS-Logo-Library/CFB%20Logos/Oregon_State_Beavers_logo-300x300.png',
    'penn state': 'FBS-Logo-Library/CFB%20Logos/Penn_State_Nittany_Lions_logo-300x300.png',
    'pittsburgh': 'FBS-Logo-Library/CFB%20Logos/Pitt_Panthers_logo-300x300.png',
    'purdue': 'FBS-Logo-Library/CFB%20Logos/Purdue_Boilermakers_logo-300x300.png',
    'rice': 'FBS-Logo-Library/CFB%20Logos/Rice_Owls_logo-300x300.png',
    'rutgers': 'FBS-Logo-Library/CFB%20Logos/Rutgers_Scarlet_Knights_logo-300x300.png',
    'sam houston': 'FBS-Logo-Library/CFB%20Logos/Sam-Houston-State-Bearkats-logo-300x300.png',
    'san diego state': 'FBS-Logo-Library/CFB%20Logos/San_Diego_State_Aztecs_logo-300x300.png',
    'san jose state': 'FBS-Logo-Library/CFB%20Logos/San_Jose_State_Spartans_logo-300x300.png',
    'smu': 'FBS-Logo-Library/CFB%20Logos/SMU_Mustang_logo-300x300.png',
    'south alabama': 'FBS-Logo-Library/CFB%20Logos/South_Alabama_Jaguars_logo-300x300.png',
    'south carolina': 'FBS-Logo-Library/CFB%20Logos/South_Carolina_Gamecocks_logo-300x300.png',
    'south florida': 'FBS-Logo-Library/CFB%20Logos/South_Florida_Bulls_logo-300x300.png',
    'southern miss': 'FBS-Logo-Library/CFB%20Logos/Southern_Miss_Golden_Eagles_logo-300x300.png',
    'stanford': 'FBS-Logo-Library/CFB%20Logos/Stanford_Cardinal_logo-300x300.png',
    'syracuse': 'FBS-Logo-Library/CFB%20Logos/Syracuse_Orange_logo-300x300.png',
    'tcu': 'FBS-Logo-Library/CFB%20Logos/TCU_Horned_Frogs_logo-300x300.png',
    'temple': 'FBS-Logo-Library/CFB%20Logos/Temple_Owls_logo-300x300.png',
    'tennessee': 'FBS-Logo-Library/CFB%20Logos/Tennessee_Volunteers_logo-300x300.png',
    'texas': 'FBS-Logo-Library/CFB%20Logos/Texas_Longhorns_logo-300x300.png',
    'texas a&m': 'FBS-Logo-Library/CFB%20Logos/Texas_AM_University_logo-300x300.png',
    'texas state': 'FBS-Logo-Library/CFB%20Logos/Texas_State_Bobcats_logo-300x300.png',
    'texas tech': 'FBS-Logo-Library/CFB%20Logos/Texas_Tech_Red_Raiders_logo-300x300.png',
    'toledo': 'FBS-Logo-Library/CFB%20Logos/Toledo_Rockets_logo-300x300.png',
    'troy': 'FBS-Logo-Library/CFB%20Logos/Troy_Trojans_logo-300x300.png',
    'tulane': 'FBS-Logo-Library/CFB%20Logos/Tulane_Green_Wave_logo-300x300.png',
    'tulsa': 'FBS-Logo-Library/CFB%20Logos/Tulsa_Golden_Hurricane_logo-300x300.png',
    'ucf': 'FBS-Logo-Library/CFB%20Logos/UCF_Knights_logo-300x300.png',
    'ucla': 'FBS-Logo-Library/CFB%20Logos/UCLA_Bruins-300x300.png',
    'uconn': 'FBS-Logo-Library/CFB%20Logos/Connecticut_Huskies_logo-300x300.png',
    'ulm': 'FBS-Logo-Library/CFB%20Logos/Louisiana-Monroe_Warhawks_logo-300x300.png',
    'unlv': 'FBS-Logo-Library/CFB%20Logos/UNLV_Rebels_logo-300x300.png',
    'usc': 'FBS-Logo-Library/CFB%20Logos/USC_Trojans_logo-300x300.png',
    'utah': 'FBS-Logo-Library/CFB%20Logos/Utah_Utes_logo-300x300.png',
    'utah state': 'FBS-Logo-Library/CFB%20Logos/Utah_State_Aggies_logo-300x300.png',
    'utep': 'FBS-Logo-Library/CFB%20Logos/UTEP-Miners-logo-300x300.png',
    'utsa': 'FBS-Logo-Library/CFB%20Logos/Texas-SA-Roadrunners-logo-300x300.png',
    'vanderbilt': 'FBS-Logo-Library/CFB%20Logos/Vanderbilt_Commodores_logo-300x300.png',
    'virginia': 'FBS-Logo-Library/CFB%20Logos/Virginia_Cavaliers_logo-300x300.png',
    'virginia tech': 'FBS-Logo-Library/CFB%20Logos/Virginia_Tech_Hokies_logo-300x300.png',
    'wake forest': 'FBS-Logo-Library/CFB%20Logos/Wake_Forest_Demon_Deacons_logo-300x300.png',
    'washington': 'FBS-Logo-Library/CFB%20Logos/Washington_Huskies_logo-300x300.png',
    'washington state': 'FBS-Logo-Library/CFB%20Logos/Washington_State_Cougars_logo-300x300.png',
    'west virginia': 'FBS-Logo-Library/CFB%20Logos/West_Virginia_Mountaineers_logo-300x300.png',
    'western kentucky': 'FBS-Logo-Library/CFB%20Logos/Western_Kentucky_Hilltoppers_logo-300x300.png',
    'western michigan': 'FBS-Logo-Library/CFB%20Logos/Western_Michigan_Broncos_logo-300x300.png',
    'wisconsin': 'FBS-Logo-Library/CFB%20Logos/Wisconsin_Badgers_logo-300x300.png',
    'wyoming': 'FBS-Logo-Library/CFB%20Logos/Wyoming_Cowboys_logo-300x300.png'
  },
  
  getTeamLogo(teamName) {
    return this.teamLogos[teamName.toLowerCase()] || '';
  },

  stadiumLocations: {
    'Air Force': 'Falcon Stadium, USAF Academy, CO',
    'Akron': 'InfoCision Stadium, Akron, OH',
    'Alabama': 'Bryant-Denny Stadium, Tuscaloosa, AL',
    'Appalachian State': 'Kidd Brewer Stadium, Boone, NC',
    'Arizona': 'Arizona Stadium, Tucson, AZ',
    'Arizona State': 'Mountain America Stadium, Tempe, AZ',
    'Arkansas': 'Reynolds Razorback Stadium, Fayetteville, AR',
    'Arkansas State': 'Centennial Bank Stadium, Jonesboro, AR',
    'Army': 'Michie Stadium, West Point, NY',
    'Auburn': 'Jordan-Hare Stadium, Auburn, AL',
    'Ball State': 'Scheumann Stadium, Muncie, IN',
    'Baylor': 'McLane Stadium, Waco, TX',
    'Boise State': 'Albertsons Stadium, Boise, ID',
    'Boston College': 'Alumni Stadium, Chestnut Hill, MA',
    'Bowling Green': 'Doyt L. Perry Stadium, Bowling Green, OH',
    'Buffalo': 'UB Stadium, Buffalo, NY',
    'BYU': 'LaVell Edwards Stadium, Provo, UT',
    'California': 'California Memorial Stadium, Berkeley, CA',
    'Central Michigan': 'Kelly/Shorts Stadium, Mount Pleasant, MI',
    'Charlotte': 'Jerry Richardson Stadium, Charlotte, NC',
    'Cincinnati': 'Nippert Stadium, Cincinnati, OH',
    'Clemson': 'Memorial Stadium, Clemson, SC',
    'Coastal Carolina': 'Brooks Stadium, Conway, SC',
    'Colorado': 'Folsom Field, Boulder, CO',
    'Colorado State': 'Canvas Stadium, Fort Collins, CO',
    'Delaware': 'Delaware Stadium, Newark, DE',
    'Duke': 'Wallace Wade Stadium, Durham, NC',
    'East Carolina': 'Dowdy-Ficklen Stadium, Greenville, NC',
    'Eastern Michigan': 'Rynearson Stadium, Ypsilanti, MI',
    'Florida Atlantic': 'FAU Stadium, Boca Raton, FL',
    'FIU': 'Pitbull Stadium, Miami, FL',
    'Florida': 'Ben Hill Griffin Stadium, Gainesville, FL',
    'Florida State': 'Doak S. Campbell Stadium, Tallahassee, FL',
    'Fresno State': 'Valley Children\'s Stadium, Fresno, CA',
    'Georgia': 'Sanford Stadium, Athens, GA',
    'Georgia Southern': 'Paulson Stadium, Statesboro, GA',
    'Georgia State': 'Center Parc Stadium, Atlanta, GA',
    'Georgia Tech': 'Bobby Dodd Stadium, Atlanta, GA',
    'Hawaiʻi': 'Clarence T. C. Ching Athletics Complex, Honolulu, HI',
    'Houston': 'TDECU Stadium, Houston, TX',
    'Illinois': 'Memorial Stadium, Champaign, IL',
    'Indiana': 'Memorial Stadium, Bloomington, IN',
    'Iowa': 'Kinnick Stadium, Iowa City, IA',
    'Iowa State': 'Jack Trice Stadium, Ames, IA',
    'Jacksonville State': 'AmFirst Stadium, Jacksonville, AL',
    'James Madison': 'Bridgeforth Stadium, Harrisonburg, VA',
    'Kansas': 'David Booth Kansas Memorial Stadium, Lawrence, KS',
    'Kansas State': 'Bill Snyder Family Stadium, Manhattan, KS',
    'Kennesaw State': 'Fifth Third Stadium, Kennesaw, GA',
    'Kent State': 'Dix Stadium, Kent, OH',
    'Kentucky': 'Kroger Field, Lexington, KY',
    'Liberty': 'Williams Stadium, Lynchburg, VA',
    'Louisiana': 'Cajun Field, Lafayette, LA',
    'Louisiana Tech': 'Joe Aillet Stadium, Ruston, LA',
    'Louisville': 'L&N Federal Credit Union Stadium, Louisville, KY',
    'LSU': 'Tiger Stadium, Baton Rouge, LA',
    'Marshall': 'Joan C. Edwards Stadium, Huntington, WV',
    'Maryland': 'SECU Stadium, College Park, MD',
    'Memphis': 'Simmons Bank Liberty Stadium, Memphis, TN',
    'Miami': 'Hard Rock Stadium, Miami Gardens, FL',
    'Miami (OH)': 'Yager Stadium, Oxford, OH',
    'Michigan': 'Michigan Stadium, Ann Arbor, MI',
    'Michigan State': 'Spartan Stadium, East Lansing, MI',
    'Middle Tennessee': 'Johnny Floyd Stadium, Murfreesboro, TN',
    'Minnesota': 'Huntington Bank Stadium, Minneapolis, MN',
    'Mississippi State': 'Davis Wade Stadium, Starkville, MS',
    'Missouri': 'Memorial Stadium, Columbia, MO',
    'Missouri State': 'Robert W. Plaster Stadium, Springfield, MO',
    'Navy': 'Navy-Marine Corps Memorial Stadium, Annapolis, MD',
    'NC State': 'Carter-Finley Stadium, Raleigh, NC',
    'Nebraska': 'Memorial Stadium, Lincoln, NE',
    'Nevada': 'Mackay Stadium, Reno, NV',
    'New Mexico': 'University Stadium, Albuquerque, NM',
    'New Mexico State': 'Aggie Memorial Stadium, Las Cruces, NM',
    'North Carolina': 'Kenan Stadium, Chapel Hill, NC',
    'North Dakota State': 'Fargodome, Fargo, ND',
    'North Texas': 'DATCU Stadium, Denton, TX',
    'Northern Illinois': 'Huskie Stadium, DeKalb, IL',
    'Northwestern': 'Ryan Field, Evanston, IL',
    'Notre Dame': 'Notre Dame Stadium, South Bend, IN',
    'Ohio': 'Peden Stadium, Athens, OH',
    'Ohio State': 'Ohio Stadium, Columbus, OH',
    'Oklahoma': 'Gaylord Family Oklahoma Memorial Stadium, Norman, OK',
    'Oklahoma State': 'Boone Pickens Stadium, Stillwater, OK',
    'Old Dominion': 'S.B. Ballard Stadium, Norfolk, VA',
    'Ole Miss': 'Vaught-Hemingway Stadium, Oxford, MS',
    'Oregon': 'Autzen Stadium, Eugene, OR',
    'Oregon State': 'Reser Stadium, Corvallis, OR',
    'Penn State': 'Beaver Stadium, University Park, PA',
    'Pittsburgh': 'Acrisure Stadium, Pittsburgh, PA',
    'Purdue': 'Ross-Ade Stadium, West Lafayette, IN',
    'Rice': 'Rice Stadium, Houston, TX',
    'Rutgers': 'SHI Stadium, Piscataway, NJ',
    'Sacramento State': 'Hornet Stadium, Sacramento, CA',
    'Sam Houston': 'Bowers Stadium, Huntsville, TX',
    'San Diego State': 'Snapdragon Stadium, San Diego, CA',
    'San Jose State': 'CEFCU Stadium, San Jose, CA',
    'SMU': 'Gerald J. Ford Stadium, University Park, TX',
    'South Alabama': 'Hancock Whitney Stadium, Mobile, AL',
    'South Carolina': 'Williams-Brice Stadium, Columbia, SC',
    'South Florida': 'Raymond James Stadium, Tampa, FL',
    'Southern Miss': 'M.M. Roberts Stadium, Hattiesburg, MS',
    'Stanford': 'Stanford Stadium, Stanford, CA',
    'Syracuse': 'JMA Wireless Dome, Syracuse, NY',
    'TCU': 'Amon G. Carter Stadium, Fort Worth, TX',
    'Temple': 'Lincoln Financial Field, Philadelphia, PA',
    'Tennessee': 'Neyland Stadium, Knoxville, TN',
    'Texas': 'Darrell K Royal-Texas Memorial Stadium, Austin, TX',
    'Texas A&M': 'Kyle Field, College Station, TX',
    'Texas State': 'UFCU Stadium, San Marcos, TX',
    'Texas Tech': 'Jones AT&T Stadium, Lubbock, TX',
    'Toledo': 'Glass Bowl, Toledo, OH',
    'Troy': 'Veterans Memorial Stadium, Troy, AL',
    'Tulane': 'Yulman Stadium, New Orleans, LA',
    'Tulsa': 'H. A. Chapman Stadium, Tulsa, OK',
    'UAB': 'Protective Stadium, Birmingham, AL',
    'UCF': 'FBC Mortgage Stadium, Orlando, FL',
    'UCLA': 'Rose Bowl, Pasadena, CA',
    'UConn': 'Rentschler Field, East Hartford, CT',
    'ULM': 'Malone Stadium, Monroe, LA',
    'UMass': 'McGuirk Alumni Stadium, Hadley, MA',
    'UNLV': 'Allegiant Stadium, Paradise, NV',
    'USC': 'Los Angeles Memorial Coliseum, Los Angeles, CA',
    'Utah': 'Rice-Eccles Stadium, Salt Lake City, UT',
    'Utah State': 'Maverik Stadium, Logan, UT',
    'UTEP': 'Sun Bowl Stadium, El Paso, TX',
    'UTSA': 'Alamodome, San Antonio, TX',
    'Vanderbilt': 'FirstBank Stadium, Nashville, TN',
    'Virginia': 'Scott Stadium, Charlottesville, VA',
    'Virginia Tech': 'Lane Stadium, Blacksburg, VA',
    'Wake Forest': 'Allegacy Federal Credit Union Stadium, Winston-Salem, NC',
    'Washington': 'Husky Stadium, Seattle, WA',
    'Washington State': 'Martin Stadium, Pullman, WA',
    'West Virginia': 'Milan Puskar Stadium, Morgantown, WV',
    'Western Kentucky': 'Houchens Industries-L. T. Smith Stadium, Bowling Green, KY',
    'Western Michigan': 'Waldo Stadium, Kalamazoo, MI',
    'Wisconsin': 'Camp Randall Stadium, Madison, WI',
    'Wyoming': 'War Memorial Stadium, Laramie, WY'
  },
  
  getStadiumLocation(teamName) {
    return this.stadiumLocations[teamName] || '';
  },

  getConference(teamName) {
    const conferences = {
      'Air Force': 'Mountain West',
      'Akron': 'MAC',
      'Alabama': 'SEC',
      'Appalachian State': 'Sun Belt',
      'Arizona': 'Big 12',
      'Arizona State': 'Big 12',
      'Arkansas': 'SEC',
      'Arkansas State': 'Sun Belt',
      'Army': 'American',
      'Auburn': 'SEC',
      'Ball State': 'MAC',
      'Baylor': 'Big 12',
      'Boise State': 'Pac-12',
      'Boston College': 'ACC',
      'Bowling Green': 'MAC',
      'Buffalo': 'MAC',
      'BYU': 'Big 12',
      'California': 'ACC',
      'Central Michigan': 'MAC',
      'Charlotte': 'American',
      'Cincinnati': 'Big 12',
      'Clemson': 'ACC',
      'Coastal Carolina': 'Sun Belt',
      'Colorado': 'Big 12',
      'Colorado State': 'Pac-12',
      'Delaware': 'CUSA',
      'Duke': 'ACC',
      'East Carolina': 'American',
      'Eastern Michigan': 'MAC',
      'Florida Atlantic': 'American',
      'FIU': 'CUSA',
      'Florida': 'SEC',
      'Florida State': 'ACC',
      'Fresno State': 'Pac-12',
      'Georgia': 'SEC',
      'Georgia Southern': 'Sun Belt',
      'Georgia State': 'Sun Belt',
      'Georgia Tech': 'ACC',
      'Hawaiʻi': 'Mountain West',
      'Houston': 'Big 12',
      'Illinois': 'Big Ten',
      'Indiana': 'Big Ten',
      'Iowa': 'Big Ten',
      'Iowa State': 'Big 12',
      'Jacksonville State': 'CUSA',
      'James Madison': 'Sun Belt',
      'Kansas': 'Big 12',
      'Kansas State': 'Big 12',
      'Kennesaw State': 'CUSA',
      'Kent State': 'MAC',
      'Kentucky': 'SEC',
      'Liberty': 'CUSA',
      'Louisiana': 'Sun Belt',
      'Louisiana Tech': 'CUSA',
      'Louisville': 'ACC',
      'LSU': 'SEC',
      'Marshall': 'Sun Belt',
      'Maryland': 'Big Ten',
      'Memphis': 'American',
      'Miami': 'ACC',
      'Miami (OH)': 'MAC',
      'Michigan': 'Big Ten',
      'Michigan State': 'Big Ten',
      'Middle Tennessee': 'CUSA',
      'Minnesota': 'Big Ten',
      'Mississippi State': 'SEC',
      'Missouri': 'SEC',
      'Missouri State': 'CUSA',
      'Navy': 'American',
      'NC State': 'ACC',
      'Nebraska': 'Big Ten',
      'Nevada': 'Mountain West',
      'New Mexico': 'Mountain West',
      'New Mexico State': 'CUSA',
      'North Carolina': 'ACC',
      'North Dakota State': 'Mountain West',
      'North Texas': 'American',
      'Northern Illinois': 'MAC',
      'Northwestern': 'Big Ten',
      'Notre Dame': 'Independent',
      'Ohio': 'MAC',
      'Ohio State': 'Big Ten',
      'Oklahoma': 'SEC',
      'Oklahoma State': 'Big 12',
      'Old Dominion': 'Sun Belt',
      'Ole Miss': 'SEC',
      'Oregon': 'Big Ten',
      'Oregon State': 'Pac-12',
      'Penn State': 'Big Ten',
      'Pittsburgh': 'ACC',
      'Purdue': 'Big Ten',
      'Rice': 'American',
      'Rutgers': 'Big Ten',
      'Sacramento State': 'MAC',
      'Sam Houston': 'CUSA',
      'San Diego State': 'Pac-12',
      'San Jose State': 'Mountain West',
      'SMU': 'ACC',
      'South Alabama': 'Sun Belt',
      'South Carolina': 'SEC',
      'South Florida': 'American',
      'Southern Miss': 'Sun Belt',
      'Stanford': 'ACC',
      'Syracuse': 'ACC',
      'TCU': 'Big 12',
      'Temple': 'American',
      'Tennessee': 'SEC',
      'Texas': 'SEC',
      'Texas A&M': 'SEC',
      'Texas State': 'Pac-12',
      'Texas Tech': 'Big 12',
      'Toledo': 'MAC',
      'Troy': 'Sun Belt',
      'Tulane': 'American',
      'Tulsa': 'American',
      'UAB': 'American',
      'UCF': 'Big 12',
      'UCLA': 'Big Ten',
      'UConn': 'Independent',
      'ULM': 'Sun Belt',
      'UMass': 'MAC',
      'UNLV': 'Mountain West',
      'USC': 'Big Ten',
      'Utah': 'Big 12',
      'Utah State': 'Pac-12',
      'UTEP': 'CUSA',
      'UTSA': 'American',
      'Vanderbilt': 'SEC',
      'Virginia': 'ACC',
      'Virginia Tech': 'ACC',
      'Wake Forest': 'ACC',
      'Washington': 'Big Ten',
      'Washington State': 'Pac-12',
      'West Virginia': 'Big 12',
      'Western Kentucky': 'CUSA',
      'Western Michigan': 'MAC',
      'Wisconsin': 'Big Ten',
      'Wyoming': 'Mountain West'
    };
    return conferences[teamName.trim()] || '';
  },

  getConferenceLogo(conferenceName) {
    const logos = {
      'ACC': 'FBS-Logo-Library/CFB%20Logos/Atlantic_Coast_Conference_ACC_logo-300x300.png',
      'American': 'FBS-Logo-Library/CFB%20Logos/American_Athletic_Conference_logo-300x300.png',
      'Big 12': 'FBS-Logo-Library/CFB%20Logos/Big_12_Conference_logo-300x300.png',
      'Big Ten': 'FBS-Logo-Library/CFB%20Logos/Big_Ten_Conference_logo-300x300.png',
      'CUSA': 'FBS-Logo-Library/CFB%20Logos/Conference_USA_logo-300x300.png',
      'MAC': 'FBS-Logo-Library/CFB%20Logos/Mid-American_Conference_logo-300x300.png',
      'Mountain West': 'FBS-Logo-Library/CFB%20Logos/Mountain_West_Conference_logo-300x300.png',
      'Pac-12': 'FBS-Logo-Library/CFB%20Logos/Pac-12_logo-300x300.png',
      'SEC': 'FBS-Logo-Library/CFB%20Logos/Southeastern_Conference_logo-300x300.png',
      'Sun Belt': 'FBS-Logo-Library/CFB%20Logos/Sun_Belt_Conference_2020_logo-300x300.png'
    };
    return logos[conferenceName] || '';
  },

  async initPage(renderCallback) {
    console.log('initPage called');
    const data = await this.load();
    if (!data) {
        console.error('initPage: failed to load data');
        return;
    }
    console.log('initPage: data loaded', data);
    const ticker = document.getElementById('score-ticker');
    if (ticker) {
      this.renderTicker(ticker, data.tickerGames, this.getRankLookup(data.dynasty.week));
    }
    renderCallback(data);
  },

  renderTicker(container, games, rankLookup) {
    if (!container) return;
    container.innerHTML = games.map(game => `
      <div class="ticker-game">
        <div class="ticker-team">
          <span class="ticker-team-name ${this.getTeamClass(game.away)}">${this.getRank(game.away.team, rankLookup)}${this.escapeHtml(game.away.team)}</span>
          <span class="ticker-score ${this.getTeamClass(game.away)}">${this.escapeHtml(game.away.score)}</span>
        </div>
        <div class="ticker-team">
          <span class="ticker-team-name ${this.getTeamClass(game.home)}">${this.getRank(game.home.team, rankLookup)}${this.escapeHtml(game.home.team)}</span>
          <span class="ticker-score ${this.getTeamClass(game.home)}">${this.escapeHtml(game.home.score)}</span>
        </div>
        <div class="ticker-status">${this.escapeHtml(game.status)}</div>
      </div>
    `).join('');
  },

  getRank(teamName, rankLookup) {
    if (!rankLookup) return '';
    const rank = rankLookup.get(teamName.toLowerCase());
    return rank ? `<span class="ticker-rank">${this.escapeHtml(rank)}</span>` : '';
  },

  getTeamClass(gameTeam) {
    return gameTeam.winner ? 'ticker-winner' : '';
  },

  renderPageNews(container, category) {
    if (!container) return;
    const news = this.getNewsByCategory(category);
    if (news.length === 0) {
      container.innerHTML = '<div class="score-info">No recent news for this category.</div>';
      return;
    }
    container.innerHTML = news.map(item => `
      <div class="headline-item">
        <div class="hl-dot">•</div>
        <div class="headline-text">${this.escapeHtml(item.title)}</div>
      </div>
    `).join('');
  }
};
